hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: ''
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: null
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - decode=cfg
    - teacher_force=false
    - teacher_force_upto=1.0
    - nonmyopic=false
    - prompt_idx=300
    - cfg_scale=20.0
  job:
    name: gt_test
    chdir: null
    override_dirname: cfg_scale=20.0,decode=cfg,nonmyopic=false,prompt_idx=300,teacher_force=false,teacher_force_upto=1.0
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.1'
    cwd: /home/server08/yoonjeon_workspace/MMAR/Show-o
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/server08/yoonjeon_workspace/MMAR/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      model_params: showo
      benchmark: mjhq
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
benchmark:
  name: mjhq
  home_dir: /home/server08/hdd1/yoonjeon_workspace/eval/
  prompts: ${benchmark.home_dir}/MJHQ_30K/meta_data.json
  outdirs: ${benchmark.home_dir}/MJHQ_30K/outputs/
  batch: 1
  save_as: image
model_params:
  model_name: Show-o
  mode: t2i
  generation_temperature: 1.0
  generation_timesteps: 50
  cfg_scale: 5.0
  model:
    vq_model:
      type: magvitv2
      vq_model_name: showlab/magvitv2
    showo:
      pretrained_model_path: showlab/show-o-512x512
      w_clip_vit: false
      vocab_size: 58498
      llm_vocab_size: 50295
      llm_model_path: microsoft/phi-1_5
      codebook_size: 8192
      num_vq_tokens: 1024
      num_new_special_tokens: 10
    gradient_checkpointing: true
  dataset:
    gen_type: t2i
    und_type: captioning
    params:
      batch_size: ${training.batch_size}
      shuffle_buffer_size: 1000
      num_workers: 32
      resolution: 512
      pin_memory: true
      persistent_workers: true
    preprocessing:
      max_seq_length: 128
      resolution: 512
      center_crop: false
      random_flip: false
  training:
    gradient_accumulation_steps: 1
    cond_dropout_prob: 0.1
    batch_size: 20
    generation_temperature: ${generation_temperature}
    generation_timesteps: ${generation_timesteps}
seed: 42
home_dir: /home/server08/hdd1/yoonjeon_workspace/eval
cd_alpha: 0.0
cd_beta: 1.0
pag_scale: 0.0
cfg_scale: 20.0
dynamic_scale: linear
prompt_idx: 300
decode: cfg
teacher_force: false
teacher_force_upto: 1.0
nonmyopic: false
wandb:
  entity: jeoni
  resume: auto
  project: ${model_params.model_name}
  sweep_name: ${model_params.model_name}
